baseURL = "/"
# canonifyURLs = true
defaultContentLanguage = "ua"
disableLanguages = ["ru"]
paginate = "6"
relativeURLs = true
summaryLength = "50"
title = "International Trade Group"
# [Languages.en]
# contentDir = "content/en"
# home = "Home"
# languageCode = "en-us"
# languageName = "En"
# weight = 3
[Languages.ru]
contentDir = "content/ru"
home = "Главная"
languageCode = "ru"
languageName = "Ру"
weight = 2
[Languages.ua]
contentDir = "content/ua"
home = "Головна"
languageCode = "uk"
languageName = "Укр"
weight = 3
[Languages.en]
contentDir = "content/en"
home = "Home"
languageCode = "en"
languageName = "ENG"
weight = 1



[outputs]
home = ["HTML", "RSS", "JSON"]
[sitemap]
ChangeFreq = "daily"
Priority = 0.6
Weight = [["main", "1"], ["sub2", "0.8"], ["sub3", "0.6"]]
enableRobotsTXT = true

[params]
CIO_site_id = "XXX"
GTM = "GTM-WHBQ3BV"
develop = "Anastasiia_Berest"
author = "ITG"

logo = "images/logo.svg"
logo_dark = "images/logo-w.svg"
logo_description = "INTERNATIONAL TRADE GROUP"

site_name = "ITG"
site_url = "#"

description = "Is a simple ecosystem of interconnected crypto products designed for the mass adoption of cryptocurrencies."

# search
search = true

# soc
tm = "https://t.me/ITG_club"

[[params.plugins.js]]
link = "plugins/js/jquery.min.js"
# [[params.plugins.js]]
# link = "plugins/js/bootstrap.bundle.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

[params.preloader]
enable = true
preloader = ""

[taxonomies]
category = "categories"
tag = "tags"


############################# socials #################################
[[params.social]]
label = "tm"
title = "Telegram"
link = "https://t.me/ITG_club"
icon = "telegram" 
icon_h = "telegram-h"
icon_sm = "tm"

[[params.social]]
label = "ytb"
title = "YouTube"
link = "https://www.youtube.com/channel/UC4Blz7CAtrKwTL8mYt6LpfA"
icon = "youtube" 
icon_h = "youtube-h"
icon_sm = "ytb"

[[params.social]]
label = "tw"
title = "Twitter"
link = "https://twitter.com/ITG_General_"
icon = "twitter" 
icon_h = "twitter-h"
icon_sm = "tw"

[[params.social]]
label = "ln"
title = "LinledIn"
link = "https://www.linkedin.com/in/international-trade-group"
icon = "linkedin" 
icon_h = "linkedin-h"
icon_sm = "ln"
soc = "false"

[[params.social]]
label = "tk"
title = "Tik-tok"
link = "http://www.tiktok.com/@itg_general__"
icon = "tiktok" 
icon_h = "tiktok-h"
icon_sm = "tk"

[[params.social]]
label = "rd"
title = "Medium"
link = "#"
icon = "medium" 
icon_h = "medium-h"
icon_sm = "md"
soc = "false"

[[params.social]]
label = "im"
title = "Instagram"
link = "https://www.instagram.com/itg_official__/"
icon_sm = "im"

[[params.social]]
label = "tn"
title = "Tradingview"
link = "https://ru.tradingview.com/u/ITG_company"
icon_sm = "tn"

[[params.social]]
label = "fb"
title = "Facebook"
link = "https://www.facebook.com/InternationalTradeGroup2018"
icon_sm = "fb"

[[params.social]]
label = "email"
title = "Email"
link = "mailto:office@itg-investments.com"
icon_sm = "email"

############################# footer #################################
[params.footer]
    copyright = "&copy; 2023 ITG Foundation. All rights reserved"

[[menu.footer]]
name = "About"
weight = 1
identifier = "about"
hasChildren = true 
    [[menu.footer]]
    parent = "about"
    name = "Company"
    URL = "/about"
    weight = 1
    [[menu.footer]]
    parent = "about"
    name = "Team"
    URL = "/team"
    weight = 2
    [[menu.footer]]
    parent = "about"
    name = "Careers"
    URL = "/works"
    weight = 3

[[menu.footer]]
name = "Products"
weight = 2
identifier = "product"
hasChildren = true
    [[menu.footer]]
    parent = "product"
    name = "ITG main"
    URL = "https://itg-main.netlify.app/"
    weight = 1
    [[menu.footer]]
    parent = "product"
    name = "Epicurus"
    URL = "https://itg-epicurus.netlify.app/"
    weight = 2
    [[menu.footer]]
    parent = "product"
    name = "ITG News"
    URL = "https://itg-news-group.netlify.app/"
    weight = 3

[[menu.footer]]
name = "Resources"
weight = 3
identifier = "resources"
hasChildren = true
    [[menu.footer]]
    parent = "resources"
    name = "FAQ"
    URL = "/faq"
    weight = 1
    [[menu.footer]]
    parent = "resources"
    name = "Wiki"
    URL = "/wiki"
    weight = 2

[[menu.footer]]
name = "Documentation"
weight = 4 
identifier = "documentation"
hasChildren = true   
    [[menu.footer]]
    parent = "documentation"
    name = "Terms and Conditions"
    URL = "/terms"
    weight = 1
    [[menu.footer]]
    parent = "documentation"
    name = "Privacy policy"
    URL = "/policy"
    weight = 2
    [[menu.footer]]
    parent = "documentation"
    name = "Terms of use"
    URL = "/terms-of-use"
    weight = 3
    [[menu.footer]]
    parent = "documentation"
    name = "Cookie policy"
    URL = "/cookie"
    weight = 4
    [[menu.footer]]
    parent = "documentation"
    name = "Risk warnings"
    URL = "/risk"
    weight = 5
[[menu.footer]]
name = "Contacts"
weight = 5    
identifier = "contacts"
hasChildren = true
    [[menu.footer]]
    parent = "contacts"
    name = "+38 050 563 58 07"
    URL = "380505635807"
    pre = "tel"
    weight = 1
    [[menu.footer]]
    parent = "contacts"
    name = "office@itg-investments.com"
    URL = "mailto:office@itg-investments.com"
    pre = "mail"
    weight = 2
    [[menu.footer]]
    parent = "contacts"
    name = "м. Київ, вул. Василя Тютюнника 28А"
    URL = "#"
    pre = "map"
    weight = 3