baseURL = "/"
# canonifyURLs = true
defaultContentLanguage = "ua"
disableLanguages = ["ru"]
paginate = "10"
relativeURLs = true
summaryLength = "50"

[Languages.en]
contentDir = "content/en"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
title = "Home"
[Languages.ru]
contentDir = "content/ru"
home = "Главная"
languageCode = "ru"
languageName = "Ру"
weight = 2
title = "Главная"
[Languages.ua]
contentDir = "content/ua"
home = "Головна"
title = "Головна"
languageCode = "uk"
languageName = "Укр"
weight = 3



[outputs]
home = ["HTML", "RSS", "JSON"]
[sitemap]
ChangeFreq = "daily"
Priority = 0.6
Weight = [["main", "1"], ["sub2", "0.8"], ["sub3", "0.6"]]
enableRobotsTXT = true

[params]
CIO_site_id = "XXX"
GTM = "GTM-WHBQ3BV"
develop = "Anastasiia_Berest"
author = "ITG"

logo = "images/logo.svg"
logo_dark = "images/logo-w.svg"
logo_description = "INTERNATIONAL TRADE GROUP"

site_name = "ITG"
site_url = "#"

description = "Is a simple ecosystem of interconnected crypto products designed for the mass adoption of cryptocurrencies."

# search
search = true

# soc
tm = "https://t.me/ITG_club"

# [[params.plugins.js]]
# link = "plugins/js/jquery.min.js"
# [[params.plugins.js]]
# link = "plugins/js/bootstrap.bundle.min.js"
# [[params.plugins.js]]
# link = "plugins/search/fuse.min.js"
# [[params.plugins.js]]
# link = "plugins/search/mark.js"
# [[params.plugins.js]]
# link = "plugins/search/search.js"

[params.preloader]
enable = true
preloader = ""

[taxonomies]
category = "categories"
tag = "tags"


############################# socials #################################
[[params.social]]
label = "tm"
title = "Telegram"
link = "https://t.me/ITG_club"
icon = "telegram" 
icon_h = "telegram-h"
icon_sm = "tm"

[[params.social]]
label = "ytb"
title = "YouTube"
link = "https://www.youtube.com/channel/UC4Blz7CAtrKwTL8mYt6LpfA"
icon = "youtube" 
icon_h = "youtube-h"
icon_sm = "ytb"

[[params.social]]
label = "tw"
title = "Twitter"
link = "https://twitter.com/ITG_General_"
icon = "twitter" 
icon_h = "twitter-h"
icon_sm = "tw"

[[params.social]]
label = "ln"
title = "LinledIn"
link = "https://www.linkedin.com/in/international-trade-group"
icon = "linkedin" 
icon_h = "linkedin-h"
icon_sm = "ln"
soc = "false"

[[params.social]]
label = "tk"
title = "Tik-tok"
link = "http://www.tiktok.com/@itg_general__"
icon = "tiktok" 
icon_h = "tiktok-h"
icon_sm = "tk"

[[params.social]]
label = "rd"
title = "Medium"
link = "#"
icon = "medium" 
icon_h = "medium-h"
icon_sm = "md"
soc = "false"

[[params.social]]
label = "im"
title = "Instagram"
link = "https://www.instagram.com/itg_official__/"
icon_sm = "im"

[[params.social]]
label = "tn"
title = "Tradingview"
link = "https://ru.tradingview.com/u/ITG_company"
icon_sm = "tn"

[[params.social]]
label = "fb"
title = "Facebook"
link = "https://www.facebook.com/InternationalTradeGroup2018"
icon_sm = "fb"

[[params.social]]
label = "email"
title = "Email"
link = "mailto:office@itg-investments.com"
icon_sm = "email"


[[Languages.ru.params.contacts]]
icon = "contacts-i1"
title = "+38 050 563 58 07"
link = "tel:380505635807"
[[Languages.ru.params.contacts]]
icon = "contacts-i2"
title = "office@itg-investments.com"
link = "mailto:office@itg-investments.com"
[[Languages.ru.params.contacts]]
icon = "contacts-i3"
title = "г. Киев, ул. Василия Тютюнника 28А"
link = "#"

[[Languages.ua.params.contacts]]
icon = "contacts-i1"
title = "+38 050 563 58 07"
link = "tel:380505635807"
[[Languages.ua.params.contacts]]
icon = "contacts-i2"
title = "office@itg-investments.com"
link = "mailto:office@itg-investments.com"
[[Languages.ua.params.contacts]]
icon = "contacts-i3"
title = "м. Київ, вул. Василя Тютюнника 28А"
link = "#"

[[Languages.en.params.contacts]]
icon = "contacts-i1"
title = "+38 050 563 58 07"
link = "tel:380505635807"
[[Languages.en.params.contacts]]
icon = "contacts-i2"
title = "office@itg-investments.com"
link = "mailto:office@itg-investments.com"
[[Languages.en.params.contacts]]
icon = "contacts-i3"
title = "Kyiv, Vasylya Tyutyunnika Street 28A"
link = "#"


[[params.soc]]
icon = "soc-tk"
link = "http://www.tiktok.com/@itg_general__"
[[params.soc]]
icon = "soc-im"
link = "https://www.instagram.com/itg_official__/"
[[params.soc]]
icon = "soc-tm"
link = "https://t.me/ITG_club"
[[params.soc]]
icon = "soc-ln"
link = "https://www.linkedin.com/in/international-trade-group"
[[params.soc]]
icon = "soc-ytb"
link = "https://www.youtube.com/channel/UC4Blz7CAtrKwTL8mYt6LpfA"

############################# header #################################
[[Languages.en.menu.main]]
URL = "/about"
name = "About"
weight = 1

[[Languages.en.menu.main]]
URL = "/services"
name = "Services"
weight = 2

[[Languages.en.menu.main]]
URL = "/job"
name = "Job"
weight = 3

[[Languages.en.menu.main]]
URL = "/blog"
name = "Blog"
weight = 4

[[Languages.en.menu.main]]
URL = "/contacts"
name = "Contacts"
weight = 4

###
[[Languages.ru.menu.main]]
URL = "/about"
name = "О нас"
weight = 1

[[Languages.ru.menu.main]]
URL = "/services"
name = "Наши услуги"
weight = 2

[[Languages.ru.menu.main]]
URL = "/job"
name = "Карьера"
weight = 3

[[Languages.ru.menu.main]]
URL = "/blog"
name = "Блог"
weight = 4

[[Languages.ru.menu.main]]
URL = "/contacts"
name = "Контакты"
weight = 4

###
[[Languages.ua.menu.main]]
URL = "/about"
name = "Про нас"
weight = 1

[[Languages.ua.menu.main]]
URL = "/services"
name = "Наші послуги"
weight = 2

[[Languages.ua.menu.main]]
URL = "/job"
name = "Кар'єра"
weight = 3

[[Languages.ua.menu.main]]
URL = "/blog"
name = "Блог"
weight = 4

[[Languages.ua.menu.main]]
URL = "/contacts"
name = "Контакти"
weight = 4

############################# footer #################################
[Languages.en.params.footer]
    copyright = "&copy; 2023 ITG Foundation. All rights reserved"
[Languages.ua.params.footer]
    copyright = "&copy; 2023 ITG Foundation. Всі права захищені."
[Languages.ru.params.footer]
    copyright = "&copy; 2023 ITG Foundation. Все права защищены"


[[Languages.en.menu.footer]]
name = "About"
weight = 1
identifier = "about"
hasChildren = true 
    [[Languages.en.menu.footer]]
    parent = "about"
    name = "Company"
    URL = "https://itg-main.netlify.app/about"
    weight = 1
    [[Languages.en.menu.footer]]
    parent = "about"
    name = "Team"
    URL = "https://itg-main.netlify.app/team/"
    weight = 2
    [[Languages.en.menu.footer]]
    parent = "about"
    name = "Careers"
    URL = "https://itg-main.netlify.app/works/"
    weight = 3

[[Languages.en.menu.footer]]
name = "Products"
weight = 2
identifier = "product"
hasChildren = true
    [[Languages.en.menu.footer]]
    parent = "product"
    name = "ITG main"
    URL = "https://itg-main.netlify.app/"
    weight = 1
    [[Languages.en.menu.footer]]
    parent = "product"
    name = "Epicurus"
    URL = "https://itg-epicurus.netlify.app/"
    weight = 2
    [[Languages.en.menu.footer]]
    parent = "product"
    name = "ITG News"
    URL = "https://itg-news-group.netlify.app/"
    weight = 3

[[Languages.en.menu.footer]]
name = "Resources"
weight = 3
identifier = "resources"
hasChildren = true
    [[Languages.en.menu.footer]]
    parent = "resources"
    name = "Blog"
    URL = "/blog"
    weight = 1
    [[Languages.en.menu.footer]]
    parent = "resources"
    name = "Cases"
    URL = "/cases"
    weight = 2

[[Languages.en.menu.footer]]
name = "Documentation"
weight = 4 
identifier = "documentation"
hasChildren = true   
    [[Languages.en.menu.footer]]
    parent = "documentation"
    name = "Terms and Conditions"
    URL = "/terms"
    weight = 1
    [[Languages.en.menu.footer]]
    parent = "documentation"
    name = "Privacy policy"
    URL = "/policy"
    weight = 2
    [[Languages.en.menu.footer]]
    parent = "documentation"
    name = "Terms of use"
    URL = "/terms-of-use"
    weight = 3
    [[Languages.en.menu.footer]]
    parent = "documentation"
    name = "Cookie policy"
    URL = "/cookie"
    weight = 4
    [[Languages.en.menu.footer]]
    parent = "documentation"
    name = "Risk warnings"
    URL = "/risk"
    weight = 5
[[Languages.en.menu.footer]]
name = "Contacts"
weight = 5    
identifier = "contacts"
hasChildren = true
    [[Languages.en.menu.footer]]
    parent = "contacts"
    name = "+38 050 563 58 07"
    URL = "380505635807"
    pre = "tel"
    weight = 1
    [[Languages.en.menu.footer]]
    parent = "contacts"
    name = "office@itg-investments.com"
    URL = "mailto:office@itg-investments.com"
    pre = "mail"
    weight = 2
    [[Languages.en.menu.footer]]
    parent = "contacts"
    name = "Kyiv, Vasylya Tyutyunnika Street 28A"
    URL = "#"
    pre = "map"
    weight = 3

###
[[Languages.ru.menu.footer]]
name = "О нас"
weight = 1
identifier = "about"
hasChildren = true 
    [[Languages.ru.menu.footer]]
    parent = "about"
    name = "Компания"
    URL = "https://itg-main.netlify.app/about"
    weight = 1
    [[Languages.ru.menu.footer]]
    parent = "about"
    name = "Команда"
    URL = "https://itg-main.netlify.app/team/"
    weight = 2
    [[Languages.ru.menu.footer]]
    parent = "about"
    name = "Вакансии"
    URL = "https://itg-main.netlify.app/works/"
    weight = 3

[[Languages.ru.menu.footer]]
name = "Продукты"
weight = 2
identifier = "product"
hasChildren = true
    [[Languages.ru.menu.footer]]
    parent = "product"
    name = "ITG main"
    URL = "https://itg-main.netlify.app/"
    weight = 1
    [[Languages.ru.menu.footer]]
    parent = "product"
    name = "Epicurus"
    URL = "https://itg-epicurus.netlify.app/"
    weight = 2
    [[Languages.ru.menu.footer]]
    parent = "product"
    name = "ITG News"
    URL = "https://itg-news-group.netlify.app/"
    weight = 3

[[Languages.ru.menu.footer]]
name = "Ресурсы"
weight = 3
identifier = "resources"
hasChildren = true
    [[Languages.ru.menu.footer]]
    parent = "resources"
    name = "Блог"
    URL = "/blog"
    weight = 1
    [[Languages.ru.menu.footer]]
    parent = "resources"
    name = "Кейсы"
    URL = "/cases"
    weight = 2

[[Languages.ru.menu.footer]]
name = "Документация"
weight = 4 
identifier = "documentation"
hasChildren = true   
    [[Languages.ru.menu.footer]]
    parent = "documentation"
    name = "Условия и положения"
    URL = "/terms"
    weight = 1
    [[Languages.ru.menu.footer]]
    parent = "documentation"
    name = "Политика конфиденциальности"
    URL = "/policy"
    weight = 2
    [[Languages.ru.menu.footer]]
    parent = "documentation"
    name = "Условия использования"
    URL = "/terms-of-use"
    weight = 3
    [[Languages.ru.menu.footer]]
    parent = "documentation"
    name = "Cookie политика"
    URL = "/cookie"
    weight = 4
    [[Languages.ru.menu.footer]]
    parent = "documentation"
    name = "Предупреждения о рисках"
    URL = "/risk"
    weight = 5
[[Languages.ru.menu.footer]]
name = "Контакты"
weight = 5    
identifier = "contacts"
hasChildren = true
    [[Languages.ru.menu.footer]]
    parent = "contacts"
    name = "+38 050 563 58 07"
    URL = "380505635807"
    pre = "tel"
    weight = 1
    [[Languages.ru.menu.footer]]
    parent = "contacts"
    name = "office@itg-investments.com"
    URL = "mailto:office@itg-investments.com"
    pre = "mail"
    weight = 2
    [[Languages.ru.menu.footer]]
    parent = "contacts"
    name = "г. Киев, ул. Василия Тютюнника 28А"
    URL = "#"
    pre = "map"
    weight = 3

###
[[Languages.ua.menu.footer]]
name = "Про нас"
weight = 1
identifier = "about"
hasChildren = true 
    [[Languages.ua.menu.footer]]
    parent = "about"
    name = "Компанія"
    URL = "https://itg-main.netlify.app/about"
    weight = 1
    [[Languages.ua.menu.footer]]
    parent = "about"
    name = "Команда"
    URL = "https://itg-main.netlify.app/team/"
    weight = 2
    [[Languages.ua.menu.footer]]
    parent = "about"
    name = "Кар'єра"
    URL = "https://itg-main.netlify.app/works/"
    weight = 3

[[Languages.ua.menu.footer]]
name = "Продукти"
weight = 2
identifier = "product"
hasChildren = true
    [[Languages.ua.menu.footer]]
    parent = "product"
    name = "ITG main"
    URL = "https://itg-main.netlify.app/"
    weight = 1
    [[Languages.ua.menu.footer]]
    parent = "product"
    name = "Epicurus"
    URL = "https://itg-epicurus.netlify.app/"
    weight = 2
    [[Languages.ua.menu.footer]]
    parent = "product"
    name = "ITG News"
    URL = "https://itg-news-group.netlify.app/"
    weight = 3

[[Languages.ua.menu.footer]]
name = "Ресурси"
weight = 3
identifier = "resources"
hasChildren = true
    [[Languages.ua.menu.footer]]
    parent = "resources"
    name = "Блог"
    URL = "/blog"
    weight = 1
    [[Languages.ua.menu.footer]]
    parent = "resources"
    name = "Кейсы"
    URL = "/cases"
    weight = 2

[[Languages.ua.menu.footer]]
name = "Документація"
weight = 4 
identifier = "documentation"
hasChildren = true   
    [[Languages.ua.menu.footer]]
    parent = "documentation"
    name = "Умови та положення"
    URL = "/terms"
    weight = 1
    [[Languages.ua.menu.footer]]
    parent = "documentation"
    name = "Політика конфіденційності"
    URL = "/policy"
    weight = 2
    [[Languages.ua.menu.footer]]
    parent = "documentation"
    name = "Умови використання"
    URL = "/terms-of-use"
    weight = 3
    [[Languages.ua.menu.footer]]
    parent = "documentation"
    name = "Cookie політика"
    URL = "/cookie"
    weight = 4
    [[Languages.ua.menu.footer]]
    parent = "documentation"
    name = "Попередження про ризики"
    URL = "/risk"
    weight = 5
[[Languages.ua.menu.footer]]
name = "Контакти"
weight = 5    
identifier = "contacts"
hasChildren = true
    [[Languages.ua.menu.footer]]
    parent = "contacts"
    name = "+38 050 563 58 07"
    URL = "380505635807"
    pre = "tel"
    weight = 1
    [[Languages.ua.menu.footer]]
    parent = "contacts"
    name = "office@itg-investments.com"
    URL = "mailto:office@itg-investments.com"
    pre = "mail"
    weight = 2
    [[Languages.ua.menu.footer]]
    parent = "contacts"
    name = "м. Київ, вул. Василя Тютюнника 28А"
    URL = "#"
    pre = "map"
    weight = 3